version: '2'

services:
    server:
        image: node:17.2.0-alpine
        user: 'node'
        restart: unless-stopped
        working_dir: /home/node/app
        environment:
            - TOKEN=${TOKEN}
            - PORT=${PORT}
            - MONGODB_URL=${MONGODB_URL}
            - WEBHOOK_ENABLED=${WEBHOOK_ENABLED}
            - WEBHOOK_URL=${WEBHOOK_URL}
            - WEBHOOK_BASE64=${WEBHOOK_BASE64}
        volumes:
            - ./:/home/node/app
        ports:
            - ${PORT}:${PORT}
        env_file:
            - .env
        command: 'npm start'
        depends_on:
            - mongo
    mongo:
        image: mongo:5.0
        environment:
            - MONGO_INITDB_DATABASE=whatsapp_api
        volumes:
            - mongo:/data/db


    mongo-express:
        image: mongo-express
        container_name: mexpress
        environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin
        links:
        - mongo
        restart: unless-stopped
        ports:
        - "8081:8081"
volumes:
    mongo:
